RaiseTogether/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from RaiseTogether.views import index
from RaiseTogether import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('categories/',include('categories.urls')),
    path('projects/',include('projects.urls')),
    path('donations/',include('donations.urls')),
    # path('adminpanel/',include('adminpanel.urls')),
    path('', index, name="homepage.index"),
    path('search/', views.search_projects, name='search_projects'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from accounts.views import Register, Profile, activate_user, login_user, logout_user , change_password , edit_profile, confirm_delete
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('register/', Register.as_view(), name = "account.create"),
    path('profile/', login_required( Profile.as_view()), name = "profile.view"),
    path('edit/', login_required(edit_profile), name = "profile.edit"),
    path('delete/', confirm_delete, name = "profile.delete.confirm"),
    path('login/', login_user , name='login'),
    path('logout/', logout_user , name='logout'),
    path('activate/<str:uidb64>/<str:token>/', activate_user, name='activate'),
    path('editPassword/', change_password, name='profile.edit.Password'),
#     path('forgetPassword/', forget_password_page, name='account.forget.password'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset/password_reset_form.html'),
         name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
         path('auth/', include('social_django.urls', namespace='social'))

    

]

donations/urls.py
from django.urls import path
from donations.views import addDonation,donationHistory,projectDonations,searchDonations,searchDonations_project
urlpatterns = [
    path('<int:project_id>', projectDonations, name="donations.project"),
    path('history/', donationHistory, name="donations.history"),
    path('donate/<int:project_id>', addDonation, name="donations.add"),
    path('search/', searchDonations, name='donations.search'),
    path('search_project/<int:project_id>', searchDonations_project, name='donations.search_project'),
]

projects/urls.py
from django.urls import path
from .views import allProjects, project_detail, add_comment, report_project, create_project, deleteProject,rate_project,myprojects,report_comment, edit_project,cancelProject,add_comment_reply,is_featured, projects_reports, comments_reports,all_featured_projects


app_name = 'projects'


urlpatterns = [
    path("", allProjects, name="all_project"),
    path('project_detail/<int:project_id>/', project_detail, name='project_detail'),
    path('add_comment/<int:project_id>/', add_comment, name='add_comment'),
    path('<int:project_id>/report/', report_project, name='report_project'),
    path('forms/create',create_project, name='projects.create' ),
    path('forms/edit/<int:project_id>',edit_project, name='projects.edit' ),
    path('<int:id>', deleteProject,name='project.delete'),
    path('cancel_project/<int:project_id>', cancelProject,name='project.cancel'),
    path('comment/report/<int:comment_id>/', report_comment, name='report_comment'),
    path('rate_project/<int:project_id>/', rate_project, name='project.rate'),
    path("myprojects/", myprojects, name="myprojects"),
    path("add_comment_reply/<int:comment_id>/", add_comment_reply, name='add_comment_reply'),
    path("is_featured/<int:project_id>/", is_featured, name='is_featured'),
    path('projects_reports/', projects_reports, name='projects.reports'),
    path('comments_reports/', comments_reports, name='comments.reports'),
    path('all_featured_projects/', all_featured_projects, name='all_featured_projects'),
]

donations/models.py
from django.db import models
from django.shortcuts import reverse
from accounts.models import MyUser
from projects.models import Project

class Donation(models.Model):

    amount = models.IntegerField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    donator = models.ForeignKey(MyUser,null=True, blank=True,on_delete=models.CASCADE, related_name='donations')
    project = models.ForeignKey(Project,null=True, blank=True,on_delete=models.CASCADE, related_name='donations')
    
    @classmethod
    def all(cls) :
        return cls.objects.all()
    
    @classmethod
    def get(cls,id) :
        return cls.objects.get(id=id)
    

donations/forms.py
from django import forms
from donations.models import  Donation
from projects.models import Project


class DonationModelForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = ['amount']

donations/views.py
from django.shortcuts import render, redirect,reverse, get_object_or_404
from donations.models import Donation
from donations.forms import DonationModelForm
from django.contrib import messages
from projects.models import Project
from django.contrib.auth.decorators import login_required
from accounts.models import MyUser


@login_required
def donationHistory(request):
    donations = Donation.objects.filter(donator=request.user)
    # donations = request.user.donations
    return render(request,'donations/history.html',{'donations':donations})

@login_required
def projectDonations(request,project_id):
    project = get_object_or_404(Project, id=project_id)
    donations = project.donations
    donations = Donation.objects.filter(project=project)
    return render(request,'donations/projectDonations.html',{'donations':donations, 'project':project})

@login_required()
def addDonation(request, project_id):
    form = DonationModelForm()
    project = get_object_or_404(Project, id=project_id)
    if request.method == 'POST':
        form = DonationModelForm(request.POST)
        if form.is_valid():
            donation = form.save() 
            donation.donator = request.user
            donation.project = project
            donation.save()
            project.current_target = project.current_target + donation.amount
            project.save()
            messages.success(request, 'Donated successfully')
            return redirect(reverse('projects:project_detail', args=[project_id]))
    return render(request, 'donations/forms/donate.html',context={"form": form})

def searchDonations(request):
    search_type = request.GET.get('search_type', 'project')
    search_query = request.GET.get('search_query', '')
    donations = []
    if search_query:
        if search_type == 'project':
            donations = Donation.objects.filter(id__in=Project.objects.filter(title__icontains=search_query).values('donations'),donator=request.user)
        elif search_type == 'amount':
            donations = Donation.objects.filter(amount=search_query,donator=request.user)
    return render(request,'donations/history.html',{'donations':donations})

def searchDonations_project(request,project_id):
    project = Project.get(project_id)
    search_type = request.GET.get('search_type', 'donator')
    search_query = request.GET.get('search_query', '')
    donations = []
    if search_query:
        if search_type == 'donator':
            donations = Donation.objects.filter(id__in=MyUser.objects.filter(username__icontains=search_query).values('donations'),project=project)
        elif search_type == 'amount':
            donations = Donation.objects.filter(amount=search_query,project=project)
    return render(request,'donations/projectDonations.html',{'donations':donations, 'project':project})

donations/templates/layouts/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'base/css/master.css'%}" rel="stylesheet" />
    <link href="{% static 'bootstrap/css/bootstrap.css'%}" rel="stylesheet" />
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet">
    <style>
      .header {
        position: sticky;
        top: 0;
        left: 0;
        width: 100%;
        z-index: 1000;
      }
    </style>
    <title>
    {% block title %}
    {% endblock %}
    </title>
    {% block style %}
    {% endblock %}
</head>
<body>
  <nav class="header navbar navbar-expand-lg navbar-light bg-white shadow-sm px-4">
    <div class="container-fluid">
      <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item my-auto ms-2">
            <a class="nav-link text-center" href="{% url 'projects:all_project' %}">
              <span class="text-success fw-bold">Explore Projects</span>
            </a>
          </li>
          <li class="nav-item my-auto ms-2"> 
            <form method="get" action="{% url 'search_projects' %}" class="d-flex mb-0" role="search" style="width: 350px;">
              <div class="input-group">
                <input type="text" name="search_query" class="form-control me-2" placeholder="Search"  style="border-radius: 17px;">
                <select name="search_type" class="form-select text-secondary me-2 flex-shrink-1"  style="border-radius: 17px; width: 20px;">
                  <option value="title">Search By Title</option>
                  <option value="tag">Search By Tag</option>
                </select>
                <button type="submit" class="btn text-success px-2" style="border-radius: 20px;"><i class="fa-brands fa-searchengin fs-5"></i></button>
              </div>
            </form>
          </li>
        </ul>
        <ul class="navbar-nav mx-auto">
          <li class="nav-item my-auto ms-2">
            <a class="nav-link fw-bold text-success fs-5" aria-current="page" href="{% url 'homepage.index' %}">
              <i class="fa-solid fa-hand-holding-dollar fs-5 text-success"></i> RaiseTogether
            </a>
          </li>
        </ul>
        <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
          <li class="nav-item my-auto ms-2">
            <a class="nav-link text-center  my-auto me-4 px-3 py-2" style="font-size: 17px;" href="{% url 'projects:projects.create' %}">
              <span class="text-success ms-3" style="font-size: 17px;">Start New Project</span>
            </a>
          </li>
          {% if user.id %}
          <div class="dropdown">
            <button class="btn btn-outline-success  dropdown-toggle border-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              {% if user.image %}
              <img src="{{ user.image.url }}" class="ms-1" width="30" height="30" style="border-radius: 50%;"/>
              {% else %}
              <img src="{% static 'base/images/no_profile_image.png' %}" class="ms-1" width="30" height="30" style="border-radius: 50%;"/>
              {% endif %}
              {{user.first_name}} {{user.last_name}}  
            </button>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item text-success" href="{% url 'profile.view' %}">My Porfile </a>
              </li>
              <li>
                <a class="dropdown-item text-success" href="{% url 'donations.history'%}">My Donations</a>
              </li>
              <li>
                <a class="dropdown-item text-success" href="{% url 'projects:myprojects' %}">My Projects</a>
              </li>
              {% if user.is_superuser %}
              <li>
                <a class="dropdown-item text-success" href="{% url 'category.list' %}">All Categories</a>
              </li>
              <li>
                <a class="dropdown-item text-success" href="{% url 'projects:projects.reports' %}">All Projects Reports</a>
              </li>
              <li>
                <a class="dropdown-item text-success" href="{% url 'projects:comments.reports' %}">All Comments Reports</a>
              </li>
              <li>
                <a class="dropdown-item text-success" href="{% url 'projects:all_featured_projects' %}">All Featured Projects</a>
              </li>
              {%endif%}
              <li>
                <a class="dropdown-item text-success" href="{% url 'logout' %}">Logout</a>
              </li>
            </ul>
          </div>
          {% else %}
          <li class="nav-item">
            <a class="nav-link text-success " href="{% url 'login' %}">Log In <i class="fa-solid fa-right-to-bracket"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-success " href="{% url 'account.create' %}">Register <i class="fa-solid fa-registered"></i></a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% if messages %}
    {% for message in messages %}
      <div class="pt-3 mx-auto" style="width: 550px;">
        <div class="alert {{ message.tags }} alert-dismissible mb-0" role="alert" >
          {{ message }}
        </div>
      </div>
    {% endfor %}
  {% endif %}
  {% block container %}
  {% endblock %}
  <footer class="text-center text-lg-start bg-light text-muted">
  <section class="d-flex justify-content-center justify-content-lg-between py-2 px-5  border-bottom">
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <div>
      <a href="" class="me-4 link-secondary"><i class="fa-brands fa-facebook"></i></a>
      <a href="" class="me-4 link-secondary"><i class="fa-brands fa-twitter"></i></a>
      <a href="" class="me-4 link-secondary"><i class="fa-brands fa-google"></i></a>
      <a href="" class="me-4 link-secondary"> <i class="fa-brands fa-instagram"></i></a>
      <a href="" class="me-4 link-secondary"><i class="fa-brands fa-linkedin"></i></a>
      <a href="https://github.com/shehabth1999/Raise-Together.git" class="me-4 link-secondary"><i class="fa-brands fa-github"></i></a>
    </div>
  </section>
  <section class="">
    <div class="container text-center text-md-start mt-3">
      <div class="row mt-3">
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-2">
          <h6 class="text-uppercase fw-bold mb-3">
            <i class="fa-solid fa-hand-holding-dollar text-success fs-1 me-1"></i> Let`s Help Each Other
          </h6>
          <p>
            You can donate through us to projects that you find worthy of your money.
            You can also create your own projects to collect donations from our customers
          </p>
        </div>
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-2 text-center">
          <h6 class="text-uppercase fw-bold mb-3">Owners</h6>
          <div class="row">
            <div class="col col-6">
              <p><a href="https://www.linkedin.com/in/shehab-tharwat" class="text-reset text-decoration-none"><i class="fa-solid fa-user text-secondary"></i> Shehab</a></p>
              <p><a href="https://www.linkedin.com/in/osamaelsaied" class="text-reset text-decoration-none"><i class="fa-solid fa-user text-secondary"></i> Fraag</a></p>
              <p><a href="https://www.linkedin.com/in/osamafraag" class="text-reset text-decoration-none"><i class="fa-solid fa-user text-secondary"></i> Mager</a></p>
            </div>
            <div class="col col-6">
              <p><a href="https://www.linkedin.com/in/reham-taher-b14a1718b" class="text-reset text-decoration-none"><i class="fa-solid fa-user text-secondary"></i> Reham</a></p>
              <p><a href="https://www.linkedin.com/in/sarasaraya" class="text-reset text-decoration-none"><i class="fa-solid fa-user text-secondary"></i> Sara</a></p>
              <p><a href="https://www.linkedin.com/in/sarahmohamed73" class="text-reset text-decoration-none"><i class="fa-solid fa-user text-secondary"></i> Sarah</a></p>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-2 text-center">
          <h6 class="text-uppercase fw-bold mb-3">Useful links</h6>
          <p class=" mb-1"><a href="{% url 'homepage.index' %}" class="text-reset btn btn-outline-dark border-0 w-50">Home</a></p>
          <p class=" mb-1"><a href="#!" class="text-reset btn btn-outline-dark border-0 w-50">Help</a></p>
          <p class=" mb-1"><a href="{% url 'projects:all_project' %}" class="text-reset btn btn-outline-dark border-0 w-50">Donate</a></p>
          <p class=" mb-1"><a href="{% url 'profile.view' %}" class="text-reset btn btn-outline-dark border-0 w-50">Profile</a></p>
        </div>
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-2">
          <h6 class="text-uppercase fw-bold mb-3">Contact</h6>
          <p><i class="fas fa-home me-3 text-secondary"></i> Mansoura, QL 10012, EG</p>
          <p><i class="fas fa-envelope me-3 text-secondary"></i> django-project@iti.com</p>
          <p><i class="fas fa-phone me-3 text-secondary"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3 text-secondary"></i> + 01 234 567 89</p>
        </div>
      </div>
    </div>

  </section>
    <div class="text-center py-2 px-5" style="background-color: rgba(0, 0, 0, 0.025);">
     © 2021 Copyright:<a class="text-reset fw-bold" href="https://mdbootstrap.com/">campaign.com</a>
    </div>
  </footer>
  <script src="{% static  'base/js/script-1.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.js'%}"></script>
  <script src="{% static 'fontawesomefree/js/fontawesome.js' %}"></script>
  <script src="{% static 'fontawesomefree/js/solid.js' %}"></script>
  <script src="{% static 'fontawesomefree/js/brands.js' %}"></script>
  {% block script %}
  {% endblock %}
</body>
</html>