RaiseTogether/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from RaiseTogether.views import index
from RaiseTogether import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('categories/',include('categories.urls')),
    path('projects/',include('projects.urls')),
    path('donations/',include('donations.urls')),
    # path('adminpanel/',include('adminpanel.urls')),
    path('', index, name="homepage.index"),
    path('search/', views.search_projects, name='search_projects'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from accounts.views import Register, Profile, activate_user, login_user, logout_user , change_password , edit_profile, confirm_delete
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('register/', Register.as_view(), name = "account.create"),
    path('profile/', login_required( Profile.as_view()), name = "profile.view"),
    path('edit/', login_required(edit_profile), name = "profile.edit"),
    path('delete/', confirm_delete, name = "profile.delete.confirm"),
    path('login/', login_user , name='login'),
    path('logout/', logout_user , name='logout'),
    path('activate/<str:uidb64>/<str:token>/', activate_user, name='activate'),
    path('editPassword/', change_password, name='profile.edit.Password'),
#     path('forgetPassword/', forget_password_page, name='account.forget.password'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset/password_reset_form.html'),
         name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
         path('auth/', include('social_django.urls', namespace='social'))

    

]

projects/urls.py
from django.urls import path
from .views import allProjects, project_detail, add_comment, report_project, create_project, deleteProject,rate_project,myprojects,report_comment, edit_project,cancelProject,add_comment_reply,is_featured, projects_reports, comments_reports,all_featured_projects


app_name = 'projects'


urlpatterns = [
    path("", allProjects, name="all_project"),
    path('project_detail/<int:project_id>/', project_detail, name='project_detail'),
    path('add_comment/<int:project_id>/', add_comment, name='add_comment'),
    path('<int:project_id>/report/', report_project, name='report_project'),
    path('forms/create',create_project, name='projects.create' ),
    path('forms/edit/<int:project_id>',edit_project, name='projects.edit' ),
    path('<int:id>', deleteProject,name='project.delete'),
    path('cancel_project/<int:project_id>', cancelProject,name='project.cancel'),
    path('comment/report/<int:comment_id>/', report_comment, name='report_comment'),
    path('rate_project/<int:project_id>/', rate_project, name='project.rate'),
    path("myprojects/", myprojects, name="myprojects"),
    path("add_comment_reply/<int:comment_id>/", add_comment_reply, name='add_comment_reply'),
    path("is_featured/<int:project_id>/", is_featured, name='is_featured'),
    path('projects_reports/', projects_reports, name='projects.reports'),
    path('comments_reports/', comments_reports, name='comments.reports'),
    path('all_featured_projects/', all_featured_projects, name='all_featured_projects'),
]

projects/forms.py
from django import forms
from .models import Multi_Picture, Project, Tag, ProjectReport, CommentReport, CommentReply
from django.forms import inlineformset_factory


class MultiPictureForm(forms.ModelForm):
    class Meta:
        model = Multi_Picture
        fields = ['image']  


MultiPictureFormSet = forms.modelformset_factory(
    Multi_Picture,
    form=MultiPictureForm,
    extra=1,
    max_num=10,  # Set a maximum number of images if needed
    validate_max=True,
)


# class ProjectForm(forms.ModelForm):
#     tags = forms.CharField(max_length=200, required=False, help_text="Enter tags separated by commas")

#     class Meta:
#         model = Project
#         # fields = ['title', 'details', 'total_target', 'start_time', 'end_time','category']
#         fields='__all__'
#         widgets = {
#             'start_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
#             'end_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
#             'tags': forms.TextInput(attrs={'placeholder': 'Enter tags separated by commas'}),
#         }

class ProjectForm(forms.ModelForm):
    tags = forms.CharField(max_length=200, required=False, help_text="Enter tags separated by commas")
    class Meta:
        model = Project
        fields = '__all__'
        title = forms.CharField(max_length=200, required=True)  # Make title field required
        details = forms.CharField(max_length=300, widget=forms.Textarea, required=True)  # Make details field required​​​​​​​​
        widgets = {
            'start_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'tags': forms.TextInput(attrs={'placeholder': 'Enter tags separated by commas'}),
        }

class ProjectReportForm(forms.ModelForm):
    class Meta:
        model = ProjectReport
        fields = ['report_reason']
        widgets = {
            'report_reason': forms.Textarea(attrs={'rows': 3}),
        }




class RatingForm(forms.Form):
    rating = forms.IntegerField(min_value=1, max_value=5)


class CommentReplyForm(forms.ModelForm):
    content = forms.CharField(label='Reply To Comment', widget=forms.Textarea)
    class Meta:
        model = CommentReply
        fields = ['content']

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse, HttpResponse
from django.urls import reverse_lazy
from .models import Project, Multi_Picture, Comment, CommentReport, Rating, Tag
from .forms import MultiPictureForm, ProjectForm, ProjectReportForm, RatingForm, CommentReplyForm, ProjectReport, CommentReport
from django.db.models import Count, Sum
from django.forms import modelformset_factory
from decimal import Decimal
from django.http import request 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from datetime import datetime

@login_required
def allProjects(request):
    active_projects = Project.objects.filter(status='Active')
    if request.user.is_superuser:
        canceled_projects = Project.objects.filter(status='Canceled')
    else:
        canceled_projects = Project.objects.filter(status='Canceled', created_by=request.user)

    return render(request, 'projects/all_project.html', context= {'active_projects': active_projects,'canceled_projects': canceled_projects})



def project_detail(request, project_id):

    project = get_object_or_404(Project, pk=project_id)
    comments = Comment.objects.filter(project=project)
    images = project.images.all()
    current_tags = project.tags.values_list('tag', flat=True)


    similar_projects = Project.objects.exclude(id=project_id) \
        .filter(tags__tag__in=current_tags) \
        .annotate(tag_count=Count('tags__tag')) \
        .order_by('-tag_count')[:4]
    
    current_target = project.current_target
    total_target = project.total_target
    percentage = (current_target / total_target) * 100


    return render(request, 'projects/project_detail.html', {
        'project': project,
        'images': images,
        'comments': comments,
        'similar_projects': similar_projects,
        'percentage':percentage,
    })


@login_required
def create_project(request):
    ImageFormSet = modelformset_factory(Multi_Picture, form=MultiPictureForm, extra=4)

    if request.method == 'POST':
        project_form = ProjectForm(request.POST, request.FILES)
        formset = ImageFormSet(request.POST, request.FILES, queryset=Multi_Picture.objects.none())

        if project_form.is_valid() and formset.is_valid():
            if request.POST.get('is_featured'):
                if not request.user.is_superuser:
                    messages.error(request, "You don't have permission")
                    return render(request, 'projects/forms/create.html', {'project_form': project_form, 'formset': formset})
            start_date = request.POST.get('start_time')
            end_date = request.POST.get('end_time')

            date_time_format = "%Y-%m-%dT%H:%M"

            start_datetime = timezone.make_aware(datetime.strptime(start_date, date_time_format))
            end_datetime = timezone.make_aware(datetime.strptime(end_date, date_time_format))

            if start_datetime < timezone.now():
                messages.error(request, "Please Enter Start Date As Now Or Future")
                return redirect('projects:projects.create')

            if end_datetime <= start_datetime:
                messages.error(request, "Please Enter End Date As A Future")
                return redirect('projects:projects.create')
            project = project_form.save()
            project.created_by = request.user
            project.save()

            tags_input = project_form.cleaned_data['tags']
            tags_list = [tag.strip() for tag in tags_input.split(',')]  # Split tags by commas
            for tag in tags_list:
                tag_obj, created = Tag.objects.get_or_create(tag=tag, project=project)

            for form in formset:
                if form.cleaned_data:
                    image = form.cleaned_data.get('image')
                    img = Multi_Picture(project=project, image=image)
                    img.save()

            print(project_form)
            return redirect('projects:project_detail', project_id=project.id)
        else:
            print("project_form.errors" , project_form.errors)
            print("formset.errors" , formset.errors)
            messages.error(request, "Check Data Again")

            return redirect('projects:projects.create')
    else:
        project_form = ProjectForm()
        formset = ImageFormSet(queryset=Multi_Picture.objects.none())
    return render(request, 'projects/forms/create.html', {'project_form': project_form, 'formset': formset})


@login_required
def edit_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    ImageFormSet = modelformset_factory(Multi_Picture, form=MultiPictureForm, extra=3, max_num=3)    
    if project.created_by == request.user or request.user.is_superuser:
        if request.method == 'POST':
            project_form = ProjectForm(request.POST, request.FILES, instance=project)

            formset = ImageFormSet(request.POST, request.FILES, queryset=Multi_Picture.objects.filter(project=project))

            if project_form.is_valid() and formset.is_valid():
                if project.is_featured and not request.user.is_superuser:
                    if request.POST.get('is_featured'):
                        messages.error(request, "You don't have permission")
                        return render(request, 'projects/forms/edit.html',
                                    {'project_form': project_form, 'formset': formset, 'project': project})

                start_date = request.POST.get('start_time')
                end_date = request.POST.get('end_time')

                date_time_format = "%Y-%m-%dT%H:%M"

                start_datetime = timezone.make_aware(datetime.strptime(start_date, date_time_format))
                end_datetime = timezone.make_aware(datetime.strptime(end_date, date_time_format))

                if start_datetime < timezone.now():
                    messages.error(request, "Please Enter Start Date As Now Or Future")
                    return redirect('projects:projects.edit', project_id)

                if end_datetime <= start_datetime:
                    messages.error(request, "Please Enter End Date As A Future")
                    return redirect('projects:projects.edit', project_id)

                project = project_form.save()

                project.images.all().delete()

                tags_input = project_form.cleaned_data.get('tags')
                tags_list = [tag.strip() for tag in tags_input.split(',')]  # Split tags by commas
                for tag in tags_list:
                    tag_obj, created = Tag.objects.get_or_create(tag=tag, project=project)

                for form in formset:
                    if form.cleaned_data:
                        image = form.cleaned_data.get('image')
                        img = Multi_Picture(project=project, image=image)
                        img.save()

                return redirect('projects:project_detail', project_id=project.id)
            else:
                messages.error(request, "Check Data Again")
        else:
            project_form = ProjectForm(instance=project)
            formset = ImageFormSet(queryset=Multi_Picture.objects.filter(project=project))
            return render(request, 'projects/forms/edit.html',
                        {'project_form': project_form, 'formset': formset, 'project': project})
    return HttpResponse('error')
            
    



@login_required
def deleteProject(request, id):
    project = Project.objects.get(id=id)
    if project.created_by == request.user or request.user.is_superuser:
        if request.method == 'POST':
            project.delete()
            return redirect('projects:all_project')
        return render(request,
                    'projects/forms/delete.html',
                    {'project': project})
    else:
        return HttpResponse('error')


@login_required
def cancelProject(request, project_id):
    project = get_object_or_404(Project, id=project_id)
 
    decimal_value = Decimal('0.25')
    donation_threshold = project.total_target * decimal_value
 
    total_donations = project.current_target 
    error_message = None

    if project.created_by == request.user or request.user.is_superuser:
        if request.method == 'POST':
            if total_donations is not None and total_donations >= donation_threshold:
                return redirect('projects:project_detail', project_id=project_id)
    
            project.status = 'Canceled'
            project.save()
            return redirect('projects:project_detail', project_id=project_id)
    
        elif total_donations is not None and total_donations >= donation_threshold:
            error_message = "Cannot cancel the project. Donations exceed or equal the threshold."
   
        return render(request,
                    'projects/forms/cancel.html',
                    {'project': project ,'donation_threshold': donation_threshold, 'total_donations': total_donations, 'error_message':error_message})
    else:
        return HttpResponse('error')


@login_required
def add_comment(request, project_id):
    if request.method == 'POST':
        content = request.POST.get('content')
        project = get_object_or_404(Project, pk=project_id)
        user = request.user
        comment = Comment(project=project, user=user, content=content)
        comment.save()
        project_id = project.pk
        return redirect(reverse('projects:project_detail', args=[project_id]))
    else:
        return render(request, 'projects/add_comment.html', {'project_id': project_id})




def report_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    if request.method == 'POST':
        form = ProjectReportForm(request.POST)
        if form.is_valid():
            report = form.save(commit=False)
            report.project = project
            report.user = request.user

projects/templates/projects/forms/cancel.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}Cancel Project{% endblock %}
{% block container %}
<div class="container p-5 my-5  shadow rounded-3 bg-white" style="width: 1000px;">
    <div class="row align-items-center">
        <img src="{% static 'projects/images/cancel_project.jpg' %}" class="col-6" width="200" />
        <div class="col-6">
            <p class="fw-bold mb-2">Are You Sure You Want To Cancel This Project?  {{ project.title }}</p>
            <form method="post">
                {% csrf_token %}
                {% if error_message %}
                    <div class="alert alert-danger">{{ error_message }}</div>
                {% else %}
                    <button type="submit" class="btn btn-danger mt-3 px-4" >Submit</button>
                {% endif %}
                
                <a href="/projects/" class="btn btn-outline-success mx-3 mt-3 px-4 " >Cancel</a>
            </form>
            <hr>
            <div class="text-center" >
              <a href="/projects" class="text-decoration-none text-success">&larr; Back to Projects</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

projects/templates/projects/forms/create.html
{% extends 'layouts/base.html' %} {% load static %} {% block title %}Add
Project{% endblock %} {% block container %}
<div class="container p-5 my-5 shadow rounded-3 bg-white" style="width: 1000px">
  <h1 class="pb-4 text-center">Create a New Project</h1>
  <div class="row align-items-center justify-content-center">
    <div class="col-10 d-flex justify-content-center">
      <img src="{% static 'projects/images/add_project.jpg' %}" height="300" />
    </div>
    <div class="col-10">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
          <label for="{{ project_form.title.id_for_label }}">Title:</label>
          <input
            type="text"
            class="form-control"
            placeholder="Enter Your Title's Project"
            name="{{ project_form.title.name }}"
          />
        </div>

        <div class="form-group">
          <label for="{{ project_form.details.id_for_label }}">Details:</label>
          <textarea
            class="form-control"
            placeholder="Enter Details About Your Project"
            name="{{ project_form.details.name }}"
          ></textarea>
        </div>
        <div class="form-group">
          <label for="{{ project_form.total_target.id_for_label }}"
            >Total Target:</label
          >
          {{ project_form.total_target }}
        </div>

        <div class="form-group">
          <label for="{{ project_form.start_time.id_for_label }}"
            >Start Time:</label
          >
          {{ project_form.start_time }}
        </div>

        <div class="form-group">
          <label for="{{ project_form.end_time.id_for_label }}"
            >End Time:</label
          >
          {{ project_form.end_time }}
        </div>

        <div class="form-group">
          <label for="{{ project_form.current_target.id_for_label }}"
            >Current Target:</label
          >
          {{ project_form.current_target }}
        </div>

        <div class="form-group">
          <label for="{{ project_form.category.id_for_label }}"
            >Category:</label
          >
          <select
            class="form-control"
            name="{{ project_form.category.name }}"
            id="{{ project_form.category.id_for_label }}"
            required
          >
            {% for category in project_form.category.field.queryset %}
            <option value="{{ category.pk }}">{{ category }}</option>
            {% endfor %}
          </select>
        </div>

        <div class="form-group">
          <label for="{{ formset.management_form.id_for_label }}">
            Images:</label
          ><br />
          {{ formset.management_form }} 
          {% for form in formset %} 
          {{form.as_table }} 
          {% endfor %}
        </div>
        <div class="form-group">
          <label for="id_tags">Tags:</label>
          <input
            type="text"
            class="form-control"
            name="tags"
            id="id_tags"
            placeholder="Enter Multi Tags separated by commas like dog , cat , etc.."
          />
        </div>
        {% if user.is_superuser%}

        <div class="form-group">
          <label for="is_featured">Is Featured</label>
          
          <input
            type="checkbox"
            class="form-control"
            name="is_featured"
            id="is_featured"
          />
          
        </div>

        {%endif%}
        <button type="submit" class="btn btn-outline-success mt-3">
          Submit
        </button>
        <hr />
      </form>
      <div class="text-center">
        <a href="/projects" class="text-decoration-none text-success"
          >&larr; Back to Projects</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock %}

projects/templates/projects/forms/delete.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} Delete Project{% endblock %}
{% block container %}
<div class="container p-5 my-5  shadow rounded-3 bg-white" style="width: 1000px;">
    <div class="row align-items-center">
        <img src="{% static 'projects/images/delete_project.jpg' %}" class="col-6" width="300" />
        <div class="col-6">
            <p class="fw-bold mb-2">Are You Sure You Want To Delete This Project?  <span class="fw-normal">{{ project.title }}</span></p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger mt-3 px-4 " >Delete</button>
                <a href="/projects/" class="btn btn-outline-success mx-3 mt-3 px-4 " >Cancel</a>
                <hr>
            </form>
            <div class="text-center" >
              <a href="/projects" class="text-decoration-none text-success">&larr; Back to Projects</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

projects/templates/projects/forms/edit.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}Edit Project{% endblock %}
{% block container %}
<div class="container p-5 my-5  shadow rounded-3 bg-white"  style="width: 1000px;">
    <h1 class="pb-4 text-center">Edit Project</h1>
    <div class="row align-items-center justify-content-center">
        <div class="col-10 d-flex justify-content-center">
            <img src="{% static 'projects/images/edit_project.jpg' %}" height="300"/>
        </div>
        <div class="col-10">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="{{ project_form.title.id_for_label }}">Title:</label>
                    {{ project_form.title }}
                </div>
        
                <div class="form-group">
                    <label for="{{ project_form.details.id_for_label }}">Details:</label>
                    {{ project_form.details }}
                </div>
        
                <div class="form-group">
                    <label for="{{ project_form.total_target.id_for_label }}">Total Target:</label>
                    {{ project_form.total_target }}
                </div>
        
                <div class="form-group">
                    <label for="{{ project_form.start_time.id_for_label }}">Start Time:</label>
                    {{ project_form.start_time }}
                </div>
        
                <div class="form-group">
                    <label for="{{ project_form.end_time.id_for_label }}">End Time:</label>
                    {{ project_form.end_time }}
                </div>
        
                <div class="form-group">
                    <label for="{{ project_form.current_target.id_for_label }}">Current Target:</label>
                    {{ project_form.current_target }}
                </div>
        
                <div class="form-group">
                    <label for="{{ project_form.category.id_for_label }}">Category:</label>
                    <select class="form-control" name="{{ project_form.category.name }}" id="{{ project_form.category.id_for_label }}" required>
                        {% for category in project_form.category.field.queryset %}
                            <option value="{{ category.pk }}">{{ category }}</option>
                        {% endfor %}
                    </select>
                </div>
        
                <div class="form-group">
                    <label for="id_tags">Tags:</label>
                    <input type="text" class="form-control" name="tags" id="id_tags" placeholder="Enter Multi Tags separated by commas like tag1, tag2, etc..">
                </div>
        
                <div class="form-group">
                    <label for="{{ formset.management_form.id_for_label }}"> Images:</label><br>
                    {{ formset.management_form }}
                    {% for form in formset %}
                        {{ form.as_table }}
                    {% endfor %}
                </div>
                {% if user.is_superuser%}
                

        <div class="form-group">
          <label for="is_featured">Is Featured</label>
          {{project_form.is_featured}}
        
          
        </div>

        {%endif%}
        
                <button type="submit" class="btn btn-outline-success text-center mt-3">Save Changes</button>
                <hr>
            </form>
            <div class="text-center" >
              <a href="/projects" class="text-decoration-none text-success">&larr; Back to Projects</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}