RaiseTogether/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from RaiseTogether.views import index
from RaiseTogether import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('categories/',include('categories.urls')),
    path('projects/',include('projects.urls')),
    path('donations/',include('donations.urls')),
    # path('adminpanel/',include('adminpanel.urls')),
    path('', index, name="homepage.index"),
    path('search/', views.search_projects, name='search_projects'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from accounts.views import Register, Profile, activate_user, login_user, logout_user , change_password , edit_profile, confirm_delete
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('register/', Register.as_view(), name = "account.create"),
    path('profile/', login_required( Profile.as_view()), name = "profile.view"),
    path('edit/', login_required(edit_profile), name = "profile.edit"),
    path('delete/', confirm_delete, name = "profile.delete.confirm"),
    path('login/', login_user , name='login'),
    path('logout/', logout_user , name='logout'),
    path('activate/<str:uidb64>/<str:token>/', activate_user, name='activate'),
    path('editPassword/', change_password, name='profile.edit.Password'),
#     path('forgetPassword/', forget_password_page, name='account.forget.password'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset/password_reset_form.html'),
         name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
         path('auth/', include('social_django.urls', namespace='social'))

    

]

projects/urls.py
from django.urls import path
from .views import allProjects, project_detail, add_comment, report_project, create_project, deleteProject,rate_project,myprojects,report_comment, edit_project,cancelProject,add_comment_reply,is_featured, projects_reports, comments_reports,all_featured_projects


app_name = 'projects'


urlpatterns = [
    path("", allProjects, name="all_project"),
    path('project_detail/<int:project_id>/', project_detail, name='project_detail'),
    path('add_comment/<int:project_id>/', add_comment, name='add_comment'),
    path('<int:project_id>/report/', report_project, name='report_project'),
    path('forms/create',create_project, name='projects.create' ),
    path('forms/edit/<int:project_id>',edit_project, name='projects.edit' ),
    path('<int:id>', deleteProject,name='project.delete'),
    path('cancel_project/<int:project_id>', cancelProject,name='project.cancel'),
    path('comment/report/<int:comment_id>/', report_comment, name='report_comment'),
    path('rate_project/<int:project_id>/', rate_project, name='project.rate'),
    path("myprojects/", myprojects, name="myprojects"),
    path("add_comment_reply/<int:comment_id>/", add_comment_reply, name='add_comment_reply'),
    path("is_featured/<int:project_id>/", is_featured, name='is_featured'),
    path('projects_reports/', projects_reports, name='projects.reports'),
    path('comments_reports/', comments_reports, name='comments.reports'),
    path('all_featured_projects/', all_featured_projects, name='all_featured_projects'),
]

projects/forms.py
from django import forms
from .models import Multi_Picture, Project, Tag, ProjectReport, CommentReport, CommentReply
from django.forms import inlineformset_factory


class MultiPictureForm(forms.ModelForm):
    class Meta:
        model = Multi_Picture
        fields = ['image']  


MultiPictureFormSet = forms.modelformset_factory(
    Multi_Picture,
    form=MultiPictureForm,
    extra=1,
    max_num=10,  # Set a maximum number of images if needed
    validate_max=True,
)


# class ProjectForm(forms.ModelForm):
#     tags = forms.CharField(max_length=200, required=False, help_text="Enter tags separated by commas")

#     class Meta:
#         model = Project
#         # fields = ['title', 'details', 'total_target', 'start_time', 'end_time','category']
#         fields='__all__'
#         widgets = {
#             'start_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
#             'end_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
#             'tags': forms.TextInput(attrs={'placeholder': 'Enter tags separated by commas'}),
#         }

class ProjectForm(forms.ModelForm):
    tags = forms.CharField(max_length=200, required=False, help_text="Enter tags separated by commas")
    class Meta:
        model = Project
        fields = '__all__'
        title = forms.CharField(max_length=200, required=True)  # Make title field required
        details = forms.CharField(max_length=300, widget=forms.Textarea, required=True)  # Make details field required​​​​​​​​
        widgets = {
            'start_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'tags': forms.TextInput(attrs={'placeholder': 'Enter tags separated by commas'}),
        }

class ProjectReportForm(forms.ModelForm):
    class Meta:
        model = ProjectReport
        fields = ['report_reason']
        widgets = {
            'report_reason': forms.Textarea(attrs={'rows': 3}),
        }




class RatingForm(forms.Form):
    rating = forms.IntegerField(min_value=1, max_value=5)


class CommentReplyForm(forms.ModelForm):
    content = forms.CharField(label='Reply To Comment', widget=forms.Textarea)
    class Meta:
        model = CommentReply
        fields = ['content']

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse, HttpResponse
from django.urls import reverse_lazy
from .models import Project, Multi_Picture, Comment, CommentReport, Rating, Tag
from .forms import MultiPictureForm, ProjectForm, ProjectReportForm, RatingForm, CommentReplyForm, ProjectReport, CommentReport
from django.db.models import Count, Sum
from django.forms import modelformset_factory
from decimal import Decimal
from django.http import request 
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from datetime import datetime

@login_required
def allProjects(request):
    active_projects = Project.objects.filter(status='Active')
    if request.user.is_superuser:
        canceled_projects = Project.objects.filter(status='Canceled')
    else:
        canceled_projects = Project.objects.filter(status='Canceled', created_by=request.user)

    return render(request, 'projects/all_project.html', context= {'active_projects': active_projects,'canceled_projects': canceled_projects})



def project_detail(request, project_id):

    project = get_object_or_404(Project, pk=project_id)
    comments = Comment.objects.filter(project=project)
    images = project.images.all()
    current_tags = project.tags.values_list('tag', flat=True)


    similar_projects = Project.objects.exclude(id=project_id) \
        .filter(tags__tag__in=current_tags) \
        .annotate(tag_count=Count('tags__tag')) \
        .order_by('-tag_count')[:4]
    
    current_target = project.current_target
    total_target = project.total_target
    percentage = (current_target / total_target) * 100


    return render(request, 'projects/project_detail.html', {
        'project': project,
        'images': images,
        'comments': comments,
        'similar_projects': similar_projects,
        'percentage':percentage,
    })


@login_required
def create_project(request):
    ImageFormSet = modelformset_factory(Multi_Picture, form=MultiPictureForm, extra=4)

    if request.method == 'POST':
        project_form = ProjectForm(request.POST, request.FILES)
        formset = ImageFormSet(request.POST, request.FILES, queryset=Multi_Picture.objects.none())

        if project_form.is_valid() and formset.is_valid():
            if request.POST.get('is_featured'):
                if not request.user.is_superuser:
                    messages.error(request, "You don't have permission")
                    return render(request, 'projects/forms/create.html', {'project_form': project_form, 'formset': formset})
            start_date = request.POST.get('start_time')
            end_date = request.POST.get('end_time')

            date_time_format = "%Y-%m-%dT%H:%M"

            start_datetime = timezone.make_aware(datetime.strptime(start_date, date_time_format))
            end_datetime = timezone.make_aware(datetime.strptime(end_date, date_time_format))

            if start_datetime < timezone.now():
                messages.error(request, "Please Enter Start Date As Now Or Future")
                return redirect('projects:projects.create')

            if end_datetime <= start_datetime:
                messages.error(request, "Please Enter End Date As A Future")
                return redirect('projects:projects.create')
            project = project_form.save()
            project.created_by = request.user
            project.save()

            tags_input = project_form.cleaned_data['tags']
            tags_list = [tag.strip() for tag in tags_input.split(',')]  # Split tags by commas
            for tag in tags_list:
                tag_obj, created = Tag.objects.get_or_create(tag=tag, project=project)

            for form in formset:
                if form.cleaned_data:
                    image = form.cleaned_data.get('image')
                    img = Multi_Picture(project=project, image=image)
                    img.save()

            print(project_form)
            return redirect('projects:project_detail', project_id=project.id)
        else:
            print("project_form.errors" , project_form.errors)
            print("formset.errors" , formset.errors)
            messages.error(request, "Check Data Again")

            return redirect('projects:projects.create')
    else:
        project_form = ProjectForm()
        formset = ImageFormSet(queryset=Multi_Picture.objects.none())
    return render(request, 'projects/forms/create.html', {'project_form': project_form, 'formset': formset})


@login_required
def edit_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    ImageFormSet = modelformset_factory(Multi_Picture, form=MultiPictureForm, extra=3, max_num=3)    
    if project.created_by == request.user or request.user.is_superuser:
        if request.method == 'POST':
            project_form = ProjectForm(request.POST, request.FILES, instance=project)

            formset = ImageFormSet(request.POST, request.FILES, queryset=Multi_Picture.objects.filter(project=project))

            if project_form.is_valid() and formset.is_valid():
                if project.is_featured and not request.user.is_superuser:
                    if request.POST.get('is_featured'):
                        messages.error(request, "You don't have permission")
                        return render(request, 'projects/forms/edit.html',
                                    {'project_form': project_form, 'formset': formset, 'project': project})

                start_date = request.POST.get('start_time')
                end_date = request.POST.get('end_time')

                date_time_format = "%Y-%m-%dT%H:%M"

                start_datetime = timezone.make_aware(datetime.strptime(start_date, date_time_format))
                end_datetime = timezone.make_aware(datetime.strptime(end_date, date_time_format))

                if start_datetime < timezone.now():
                    messages.error(request, "Please Enter Start Date As Now Or Future")
                    return redirect('projects:projects.edit', project_id)

                if end_datetime <= start_datetime:
                    messages.error(request, "Please Enter End Date As A Future")
                    return redirect('projects:projects.edit', project_id)

                project = project_form.save()

                project.images.all().delete()

                tags_input = project_form.cleaned_data.get('tags')
                tags_list = [tag.strip() for tag in tags_input.split(',')]  # Split tags by commas
                for tag in tags_list:
                    tag_obj, created = Tag.objects.get_or_create(tag=tag, project=project)

                for form in formset:
                    if form.cleaned_data:
                        image = form.cleaned_data.get('image')
                        img = Multi_Picture(project=project, image=image)
                        img.save()

                return redirect('projects:project_detail', project_id=project.id)
            else:
                messages.error(request, "Check Data Again")
        else:
            project_form = ProjectForm(instance=project)
            formset = ImageFormSet(queryset=Multi_Picture.objects.filter(project=project))
            return render(request, 'projects/forms/edit.html',
                        {'project_form': project_form, 'formset': formset, 'project': project})
    return HttpResponse('error')
            
    



@login_required
def deleteProject(request, id):
    project = Project.objects.get(id=id)
    if project.created_by == request.user or request.user.is_superuser:
        if request.method == 'POST':
            project.delete()
            return redirect('projects:all_project')
        return render(request,
                    'projects/forms/delete.html',
                    {'project': project})
    else:
        return HttpResponse('error')


@login_required
def cancelProject(request, project_id):
    project = get_object_or_404(Project, id=project_id)
 
    decimal_value = Decimal('0.25')
    donation_threshold = project.total_target * decimal_value
 
    total_donations = project.current_target 
    error_message = None

    if project.created_by == request.user or request.user.is_superuser:
        if request.method == 'POST':
            if total_donations is not None and total_donations >= donation_threshold:
                return redirect('projects:project_detail', project_id=project_id)
    
            project.status = 'Canceled'
            project.save()
            return redirect('projects:project_detail', project_id=project_id)
    
        elif total_donations is not None and total_donations >= donation_threshold:
            error_message = "Cannot cancel the project. Donations exceed or equal the threshold."
   
        return render(request,
                    'projects/forms/cancel.html',
                    {'project': project ,'donation_threshold': donation_threshold, 'total_donations': total_donations, 'error_message':error_message})
    else:
        return HttpResponse('error')


@login_required
def add_comment(request, project_id):
    if request.method == 'POST':
        content = request.POST.get('content')
        project = get_object_or_404(Project, pk=project_id)
        user = request.user
        comment = Comment(project=project, user=user, content=content)
        comment.save()
        project_id = project.pk
        return redirect(reverse('projects:project_detail', args=[project_id]))
    else:
        return render(request, 'projects/add_comment.html', {'project_id': project_id})




def report_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    if request.method == 'POST':
        form = ProjectReportForm(request.POST)
        if form.is_valid():
            report = form.save(commit=False)
            report.project = project
            report.user = request.user

projects/templates/projects/add_comment.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}Add Comment{% endblock %}
{% block container %}
<div class="container p-5 my-5  shadow rounded-3 bg-white" style="width: 1000px;">
    <div class="row align-items-center">
        <img src="{% static 'projects/images/comment.jpg' %}" class="col-6" width="300" />
        <div class="col-6">
            <form method="post">
                {% csrf_token %}
                <label for="content" class="form-label">Comment</label>
                <textarea class="form-control mb-3" id="content" rows="3"  name="content"></textarea>
                <button type="submit" class="btn btn-outline-success text-center">Add Comment</button>
                <hr>
            </form>
            <div class="text-center" >
                <a href="/projects" class="text-decoration-none text-success">&larr; Back to Projects</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

projects/templates/projects/add_comment_reply.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block title %}
    Add Comment Reply
{% endblock %}

{% block container %}
<div class="container p-5 my-5  shadow rounded-3 bg-white" style="width: 1000px;">
    <div class="row align-items-center">
        <img src="{% static 'projects/images/comment.jpg' %}" class="col-6" width="300" />
        <div class="col-6">
            <form method="post">
              {% csrf_token %}
              {{ reply_form.as_p }}
              <button type="submit" class="btn btn-outline-success">Submit</button>
            </form>
            <hr>
            <div class="text-center" >
                <a href="/projects" class="text-decoration-none text-success">&larr; Back to Projects</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

projects/templates/projects/all_featured_projects.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} All Featured Projects {% endblock %}
{% block container %}
<div class="container p-5 my-5  shadow rounded-3 bg-white" style="width: 1000px;">
  <div class="header">
    <h4 class="text-success text-uppercase">Reports</h4>
    <p class="text-secondary">All Featured Projects</p>
  </div>
  {% if featured_projects %}
  <table class="table">
    <thead class="table-light table-hover">
      <tr>
        <th class="text-uppercase">Project Name</th>
        <th class="text-uppercase">Project Owner</th>
        <th class="text-uppercase">Remove From Featured</th>
      </tr>
    </thead>
    <tbody>
      
      {% for featured_project in featured_projects %}
      <tr>
        <td>{{featured_project.title}}</td>
        <td>{{featured_project.created_by}}</td>
        <td>
          <a href="{% url 'projects:is_featured' featured_project.id %}" class="btn text-success p-0 mx-2"> 
            <i class="fa-regular fa-thumbs-down"></i>
        </i></a>
        </td>
      </tr>
      {% endfor %}
     
    </tbody>
  </table>
  {% else %}
    <h5 class="text-center">No Reports Available.</h5>
  {% endif %}
</div>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} {{project.title}}{% endblock %}
{% block container %}
<div class="container py-5">
    <div class="row justify-content-evenly">
        <h3 class="mb-4" style="margin-left: 9rem;">{{project.title}}</h3>
        <div class="col-6">
            <!-- Images Slider -->
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel" style="height: 500px;">
                <div class="carousel-inner">
                {% for image in project.images.all %}
                <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
                    <img src="{{image.get_image_url}}" class="d-block w-100 h-100" alt="..." >
                </div>
                {% endfor %}
                </div>
            </div>
            <!-- Owner -->
            <p class="fs-5 my-3">
                {% if project.created_by.image %}
                <img src="{{ project.created_by.image.url }}" class="me-3" width="30" height="30" style="border-radius: 50%;"/>
                {% else %}
                <img src="{% static 'base/images/no_profile_image.png' %}" class="ms-1" width="30" height="30" style="border-radius: 50%;"/>
                {% endif %}
                {{project.created_by.first_name}} {{project.created_by.last_name}} is Owner this Project.
                {% if user == project.created_by or user.is_superuser %}
                <a href="{% url 'projects:projects.edit' project.id%}" class="btn text-success p-0 mx-2"><i class="fa-regular fa-pen-to-square"></i></a>
               
                <a href="{% url 'projects:project.delete' project.id%}" class="btn text-danger p-0 mx-2"><i class="fa-solid fa-x"></i></a>

                <a href="{% url 'projects:project.cancel' project.id%}" class="btn text-danger p-0 mx-2"><i class="fa-solid fa-ban"></i></a>
                {% endif %}
                {% if user.is_superuser %}
                <a href="{% url 'projects:is_featured' project.id %}" class="btn text-success p-0 mx-2"> 
                    {% if project.is_featured %}
                    <i class="fa-regular fa-thumbs-down"></i>
                    {% else %}
                    <i class="fa-regular fa-thumbs-up"></i>
                    {% endif %}

                </i></a>
                {% endif %}
                
            </p>
            <hr>

            <!-- Details - Tags -->
            <p class="lh-lg fs-5 mb-0 overflow-auto" style="letter-spacing: 1px;">
                {{project.details}}
            </p>
            <p class="text-secondary ">
                {% for tag in project.tags.all %}
                <small class="me-3">{{tag.tag}}</small>
                {% endfor %}
            </p>
            <hr>
            <!-- Links -->
            <div class="links row justify-content-center my-4">
                <a href="{% url 'donations.add' project.id %}" class="col-5 btn btn-success py-2 me-4 fs-5" style="border-radius: 15px;">Donate <i class="fa-solid fa-hand-holding-dollar"></i></a>
                <a href="{% url 'projects:project.rate' project.id %}" class="col-5 btn btn-outline-success py-2 fs-5" style="border-radius: 15px;">Rate <i class="fa-solid fa-star"></i></a>
            </div>
            <hr>

            <!-- Comment -->
            <div class="comments my-4">
                <div class="add-comment d-flex justify-content-between align-items-center">
                    <h4>Words of Support ({{ project.comments.all|length }})</h4>
                    <a class="btn text-success my-3 " href="{% url 'projects:add_comment' project_id=project.id %}"><i class="fa-regular fa-comment fs-3 me-5"></i></a>
                </div> 
                {% for comment in comments %}
                <div class="comment mb-5">
                    <div class="user-info">
                        <span>
                            {% if comment.user.image %}
                            <img src="{{ comment.user.image.url }}" class="me-3" width="30" height="30" style="border-radius: 50%;"/>
                            {% else %}
                            <img src="{% static 'base/images/no_profile_image.png' %}" class="ms-1" width="30" height="30" style="border-radius: 50%;"/>
                            {% endif %}
                            {{comment.user.first_name}} {{comment.user.last_name}}
                        </span>
                        <small class="text-secondary ms-5">Created {{ comment.created_at|timesince }} ago</small>
                        <p class="ms-5 mt-3" style="font-size: 19px;"> 
                            {{ comment.content }}
                            <a href="{% url 'projects:add_comment_reply' comment_id=comment.id %}" class="text-success me-5 text-decoration-none"><i class="fa-solid fa-reply mx-5"></i></a> 
                            <a href="{% url 'projects:report_comment' comment_id=comment.id %}" class="text-success me-5"><i class="fa-solid fa-bug fs-6"></i></a>
                        </p>
                        <!-- Replies -->
                        <div class="replies ms-5">
                            {% for reply in comment.replies.all %}
                            <div class="reply mb-4">
                                <span>
                                    {% if reply.user.image %}
                                    <img src="{{ reply.user.image.url }}" class="me-3" width="30" height="30" style="border-radius: 50%;"/>
                                    {% else %}
                                    <img src="{% static 'base/images/no_profile_image.png' %}" class="ms-1" width="30" height="30" style="border-radius: 50%;"/>
                                    {% endif %}
                                    {{reply.user.first_name}} {{reply.user.last_name}}
                                </span>
                                <small class="text-secondary ms-5">Created {{ reply.created_at|timesince }} ago</small>
                                <p class="ms-5 mt-3" style="font-size: 19px;"> 
                                    {{ reply.content }} 
                                </p>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- --------------------------------------------------- -->
        <div class="col-4 p-4 shadow" style="border-radius: 20px; height: 830px; max-height: 1500px;">
            <!-- Donation -->
            <div class="donation mb-3">
                <p class="fs-4 d-inline-block mb-0">${{project.current_target}}</p>
                <small class="text-secondary">USD raised of ${{project.total_target}} goal</small>
            </div>
            <div class="progress mb-3" style="height: 7px; background-color: #02a95c1f;">
                <div class="progress-bar  bg-success" role="progressbar" style="width: {{ percentage }}%; height: 7px" aria-valuenow="{{ percentage }}" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <p class="text-secondary">{{ project.donations.count }} donation</p>
            <hr>

            <div class="some-info">
                <p class="fs-5"><i class="fa-regular fa-calendar text-success"></i> <small class="fs-6 text-secondary">{{ project.start_time|date:'m - d - Y' }} : {{ project.end_time|date:'m - d - Y' }}</small></p>

                <p class="fs-5"><i class="fa-solid fa-star text-success"></i> <small class="fs-6 text-secondary">{{ project.rating }}</small></p>

                <p class="fs-5"><i class="fa-solid fa-qrcode text-success"></i> <small class="fs-6 text-secondary">{{ project.category }}</small></p>
            </div>
            <hr>

            <div class="links row justify-content-center my-4">
                <a href="{% url 'donations.add' project.id %}" class="col-10 btn btn-success py-2 me-4 mb-3 fs-5" style="border-radius: 15px;">Donate <i class="fa-solid fa-hand-holding-dollar"></i></a>
                <a href="{% url 'projects:report_project' project.id %}" class="col-10 btn btn-outline-success py-2 me-4 fs-5" style="border-radius: 15px;">Report <i class="fa-solid fa-bug"></i></a>
            </div>

            <div class="donations my-4">
                {% for donation in project.donations.all|slice:":3" %}
                <div class="comment mb-5">
                    <div class="user-info">
                        <span>
                            <img src="{{ donation.donator.image.url }}" class="me-3 rounded-5" width="30" height="30"/>
                            {{donation.donator.first_name}} {{donation.donator.last_name}}
                        </span>
                        <span class="text-secondary ms-5">
                            <small class="text-dark fw-bold me-4 ms-1">${{ donation.amount }}</small>
                            <small>{{ donation.created_at|timesince }} ago</small>
                        </span>
                    </div>
                </div>
                {% endfor %}
                {% if project.donations.all %} 
                <div class="text-center">
                    <a href="{% url 'donations.project' project.id %}" class="btn btn-outline-success">See All Donations</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- ------------------- Simliar Projects --------------------- -->
    <hr>
    <h3 class="py-4">Similar Projects</h3>
    {% if similar_projects %}
    <div class="row row-cols-1 row-cols-md-4 justify-content-center g-4">
        {% for project in similar_projects %}
          <div class="col">
            <div class="card border-0 shadow-sm bg-light">
              <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                  {% for image in project.images.all %}
                  <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
                    <img src="{{image.get_image_url}}" class="d-block w-100 rounded-3" alt="..." style="height: 200px;">
                  </div>
                  {% endfor %}
                </div>
              </div>
              
              <div class="card-body">
                <h5 class="card-title"><span class="truncated">{{ project.title|slice:":25" }}</span></h5>
                <p class="card-text"><small style="font-weight: 500;">Finish At: </small><small class="text-body-secondary">{{ project.end_time|date:'m - d - Y' }}</small></p>
                <div class="d-flex justify-content-between align-items-end mt-4">
                  <a href="{% url 'donations.add' project.id %}" class="btn text-success p-0"><i class="fa-solid fa-hand-holding-dollar"></i></a>
                  {% if user == project.created_by or user.is_superuser %}
                  <a href="{% url 'projects:projects.edit' project.id%}" class="btn text-success p-0"><i class="fa-regular fa-pen-to-square"></i></a>
                  <a href="{% url 'projects:project.delete' project.id%}" class="btn text-danger p-0"><i class="fa-solid fa-x"></i></a>
                  {% endif %}
                  <a href="{% url 'projects:project_detail' project.id %}" class="btn text-success p-0"><i class="fa-solid fa-circle-info"></i></a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
    </div>
    {% else %}
        <p class="fs-5 text-center">Sorry There Is No Similar Project Now!</p>
    {% endif %}
</div>
{% endblock %}