RaiseTogether/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from RaiseTogether.views import index
from RaiseTogether import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('categories/',include('categories.urls')),
    path('projects/',include('projects.urls')),
    path('donations/',include('donations.urls')),
    # path('adminpanel/',include('adminpanel.urls')),
    path('', index, name="homepage.index"),
    path('search/', views.search_projects, name='search_projects'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from accounts.views import Register, Profile, activate_user, login_user, logout_user , change_password , edit_profile, confirm_delete
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('register/', Register.as_view(), name = "account.create"),
    path('profile/', login_required( Profile.as_view()), name = "profile.view"),
    path('edit/', login_required(edit_profile), name = "profile.edit"),
    path('delete/', confirm_delete, name = "profile.delete.confirm"),
    path('login/', login_user , name='login'),
    path('logout/', logout_user , name='logout'),
    path('activate/<str:uidb64>/<str:token>/', activate_user, name='activate'),
    path('editPassword/', change_password, name='profile.edit.Password'),
#     path('forgetPassword/', forget_password_page, name='account.forget.password'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset/password_reset_form.html'),
         name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/password_reset_complete.html'),
         name='password_reset_complete'),
         path('auth/', include('social_django.urls', namespace='social'))

    

]

categories/urls.py
from django.urls import path
from categories.views import CategoryListView, CategoryDetailView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from django.contrib.auth.decorators import user_passes_test

urlpatterns = [
    path('', CategoryListView.as_view(), name='category.list'),
    path('<int:category_id>/', CategoryDetailView.as_view(), name='category.detail'),
    path('create/', CategoryCreateView.as_view(), name='category.create'),
    path('edit/<int:category_id>/', CategoryUpdateView.as_view(), name='category.edit'),
    path('delete/<int:category_id>/', CategoryDeleteView.as_view(), name='category.delete'),
]

projects/urls.py
from django.urls import path
from .views import allProjects, project_detail, add_comment, report_project, create_project, deleteProject,rate_project,myprojects,report_comment, edit_project,cancelProject,add_comment_reply,is_featured, projects_reports, comments_reports,all_featured_projects


app_name = 'projects'


urlpatterns = [
    path("", allProjects, name="all_project"),
    path('project_detail/<int:project_id>/', project_detail, name='project_detail'),
    path('add_comment/<int:project_id>/', add_comment, name='add_comment'),
    path('<int:project_id>/report/', report_project, name='report_project'),
    path('forms/create',create_project, name='projects.create' ),
    path('forms/edit/<int:project_id>',edit_project, name='projects.edit' ),
    path('<int:id>', deleteProject,name='project.delete'),
    path('cancel_project/<int:project_id>', cancelProject,name='project.cancel'),
    path('comment/report/<int:comment_id>/', report_comment, name='report_comment'),
    path('rate_project/<int:project_id>/', rate_project, name='project.rate'),
    path("myprojects/", myprojects, name="myprojects"),
    path("add_comment_reply/<int:comment_id>/", add_comment_reply, name='add_comment_reply'),
    path("is_featured/<int:project_id>/", is_featured, name='is_featured'),
    path('projects_reports/', projects_reports, name='projects.reports'),
    path('comments_reports/', comments_reports, name='comments.reports'),
    path('all_featured_projects/', all_featured_projects, name='all_featured_projects'),
]

categories/models.py
from django.db import models
from django.shortcuts import  reverse

# Create your models here.
class Category(models.Model):
  name = models.CharField(max_length=100, unique=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return f"{self.name}"
  
  @classmethod
  def get_all_categories(cls):
    return  cls.objects.all()
  
  def get_show_url(self):
    return  reverse('category.detail', args=[self.id])

categories/forms.py
from django import forms
from .models import Category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

categories/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.urls import reverse
from .models import Category
from .forms import CategoryForm
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin

class SuperuserRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser
    
    def handle_no_permission(self):
        return render(self.request, 'categories/no_permission_template.html')

class CategoryListView(SuperuserRequiredMixin, View):
    template_name = 'categories/categories.html'

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all().order_by('id')
        return render(request, self.template_name, {'categories': categories})


class CategoryDetailView(View):
    template_name = 'categories/show.html'

    def get(self, request, category_id, *args, **kwargs):
        category = get_object_or_404(Category, id=category_id)
        return render(request, self.template_name, {'category': category})


class CategoryCreateView(SuperuserRequiredMixin, View):
    template_name = 'categories/create.html'

    def get(self, request, *args, **kwargs):
        form = CategoryForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('category.list'))
        return render(request, self.template_name, {'form': form})


class CategoryUpdateView(SuperuserRequiredMixin, View):
    template_name = 'categories/edit.html'

    def get(self, request, category_id, *args, **kwargs):
        category = get_object_or_404(Category, id=category_id)
        form = CategoryForm(instance=category)
        return render(request, self.template_name, {'form': form, 'category': category})

    def post(self, request, category_id, *args, **kwargs):
        category = get_object_or_404(Category, id=category_id)
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect(reverse('category.list'))
        return render(request, self.template_name, {'form': form, 'category': category})


class CategoryDeleteView(SuperuserRequiredMixin, View):
    template_name = 'categories/delete.html'

    def get(self, request, category_id, *args, **kwargs):
        category = get_object_or_404(Category, id=category_id)
        return render(request, self.template_name, {'category': category})

    def post(self, request, category_id, *args, **kwargs):
        category = get_object_or_404(Category, id=category_id)
        if not category.projects.all():
            category.delete()
            return redirect(reverse('category.list'))
        messages.error(request, "Can't Remove! This Category Has Projects!")
        return redirect(reverse('category.list'))

categories/templates/categories/categories.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}{{category.name}}{% endblock %}
{% block container %}

<div class="p-5 mx-4">
<div >
    <a href="{% url 'category.create' %}" class="text-success fs-4"><i class="fa-solid fa-square-plus"></i></a>
  </div>
  <table class="table my-5" id="dataTable" width="100%" cellspacing="0">
    <tr class="bg-success text-white">
      <th class="py-3">ID</th>  
      <th class="py-3">Name</th>
      <th class="py-3">Show</th>
      <th class="py-3">Edit</th>
      <th class="py-3">Delete</th>
    </tr>
 
    {% for category in categories %}
      <tr>
        <td>{{category.id}}</td>
        <td>{{category.name}}</td>
        <td>
          <a href="{{category.get_show_url}}" class="btn text-success ">
            <i class="fa-regular fa-eye"></i>
          </a>
        </td>
        <td>
          <a href="{% url 'category.edit' category.id %}" class="btn text-success ">
            <i class="fa-regular fa-pen-to-square"></i>
          </a>
        </td>
        <td>
          {% if not category.projects.all %}
          <a href="{% url 'category.delete' category.id %}" class="btn text-danger">
            <i class="fa-solid fa-minus"></i>
          </a>
          {% endif %}
        </td>
           
      </tr>
    {% endfor %}
  </table>

</div>
{% endblock %}

categories/templates/categories/create.html
{% extends 'layouts/base.html' %} {% load static %} {% block title %}Add
Category{% endblock %} {% block container %}
<div class="container p-5 my-5 shadow rounded-3 bg-white" style="width: 1000px">
  <h1 class="pb-4 text-center">Create a New Category</h1>
  <div class="row align-items-center justify-content-center">
    <div class="col-10 d-flex justify-content-center">
      <img src="{% static 'projects/images/add_project.jpg' %}" height="300" />
    </div>
    <div class="col-10">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
{{form}}
        <button type="submit" class="btn btn-outline-success mt-3">
          Submit
        </button>
        <hr />
      </form>
      <div class="text-center">
        <a href="/projects" class="text-decoration-none text-success"
          >&larr; Back to Projects</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock %}

categories/templates/categories/delete.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %} Delete {{category}}{% endblock %}
{% block container %}
<div class="container p-5 my-5  shadow rounded-3 bg-white" style="width: 1000px;">
    <div class="row align-items-center">
        <img src="{% static 'projects/images/delete_project.jpg' %}" class="col-6" width="300" />
        <div class="col-6">
            <p class="fw-bold mb-2">Are You Sure You Want To Delete This Category?  <span class="fw-normal">{{ project.title }}</span></p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger mt-3 px-4 " >Delete</button>
                <a href="/categories/" class="btn btn-outline-success mx-3 mt-3 px-4 " >Cancel</a>
                <hr>
            </form>
            <div class="text-center" >
            </div>
        </div>
    </div>
</div>
{% endblock %}

categories/templates/categories/edit.html
{% extends 'layouts/base.html' %} {% load static %} {% block title %}Edit
Category{% endblock %} {% block container %}
<div class="container p-5 my-5 shadow rounded-3 bg-white" style="width: 1000px">
  <h1 class="pb-4 text-center">Edit {{category}}</h1>
  <div class="row align-items-center justify-content-center">
    <div class="col-10 d-flex justify-content-center">
      <img src="{% static 'projects/images/edit_project.jpg' %}" height="300" />
    </div>
    <div class="col-10">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %} {{form}}

        <button type="submit" class="btn btn-outline-success text-center mt-3">
          Save Changes
        </button>
        <hr />
      </form>
    </div>
  </div>
</div>
{% endblock %}

categories/templates/categories/no_permission_template.html
{% extends 'layouts/base.html' %} {% load static %} {% block title %} No permission {% endblock %} {% block container %}
<div class="container p-5 my-5 shadow rounded-3 bg-white" style="width: 1000px">
  <h1 class="pb-4 text-center">You don't have permission!</h1>
  <div class="row align-items-center justify-content-center">
    <div class="col-10 d-flex justify-content-center">
      <img src="{% static 'projects/images/no-permission.jpeg' %}" height="300" />
    </div>
  </div>
</div>
{% endblock %}

categories/templates/categories/show.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block title %}{{category.name}}{% endblock %}
{% block container %}
  <div class="container py-5">
    <h2 class="pb-2">{{category.name}}</h2>
    <div class="row row-cols-1 row-cols-md-4 justify-content-center g-4">
    {% for project in category.projects.all%}
      <div class="col">
        <div class="card border-0 shadow-sm bg-light">
          <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              {% for image in project.images.all %}
              <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
                <img src="{{image.get_image_url}}" class="d-block w-100 rounded-3" alt="..." style="height: 300px;">
              </div>
              {% endfor %}
            </div>
          </div>
          
          <div class="card-body">
            <h5 class="card-title">{{ project.title|slice:":25" }}</h5>
            <p class="card-text"><small style="font-weight: 500;">Will Finish At: </small><small class="text-body-secondary">{{ project.end_time|date:'m - d - Y' }}</small></p>
            <div class="d-flex justify-content-between align-items-end mt-4">
              <a href="{% url 'donations.add' project.id %}" class="btn text-success p-0"><i class="fa-solid fa-hand-holding-dollar"></i></a>
              {% if user == project.created_by or user.is_superuser %}
              <a href="{% url 'projects:projects.edit' project.id%}" class="btn text-success p-0"><i class="fa-regular fa-pen-to-square"></i></a>
              <a href="{% url 'projects:project.delete' project.id%}" class="btn text-danger p-0"><i class="fa-solid fa-x"></i></a>
              {% endif %}
              <a href="{% url 'projects:project_detail' project.id %}" class="btn text-success p-0"><i class="fa-solid fa-circle-info"></i></a>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
{% endblock %}